const dataPath = 'src/data.json';
const outputPath = 'src/asset-imports.js';

async function findImagePaths(obj) {
  let imagePaths = [];

  for (const key in obj) {
    if (typeof obj[key] === 'object' && obj[key] !== null) {
      imagePaths = imagePaths.concat(await findImagePaths(obj[key]));
    } else if (key === 'imagen' && typeof obj[key] === 'string') {
      imagePaths.push(obj[key]);
    }
  }

  return imagePaths;
}

async function generateAssetImports() {
  try {
    const dataFile = Bun.file(dataPath);
    const dataContent = await dataFile.text();
    const data = JSON.parse(dataContent);

    const imagePaths = await findImagePaths(data);
    const uniqueImagePaths = [...new Set(imagePaths)]; // Remove duplicates

    const importStatements = uniqueImagePaths
      .map((p, i) => `import img${i} from './assets/${p}';`)
      .join('\n');

    const exportMap = uniqueImagePaths
      .map((p, i) => `  "${p}": img${i},`)
      .join('\n');

    const fileContent = `// This file is auto-generated by scripts/prepare-assets.js
// Do not edit this file directly.

${importStatements}

export default {
${exportMap}
};
`;

    await Bun.write(outputPath, fileContent);
    console.log(`✅ Asset imports generated at ${outputPath}`);
  } catch (error) {
    console.error('Error generating asset imports:', error);
    process.exit(1);
  }
}

generateAssetImports();
