// This file is auto-generated by scripts/prepare-assets.js
// Do not edit this file directly.

import img0 from './assets/bolsa-mini.png';
import img1 from './assets/bolsa-mediana.png';
import img2 from './assets/bolsa-grande.png';
import img3 from './assets/bolsa-jumbo.png';
import img4 from './assets/bolsa-botillera.png';
import img5 from './assets/rollo-pullpack-700.png';
import img6 from './assets/bolsa-de-ensalada.png';
import img7 from './assets/bolsa-taco-manga.png';
import img8 from './assets/guante-de-nitrilo.png';
import img9 from './assets/guante-de-vinilo.png';
import img10 from './assets/guantes-polietileno.png';
import img11 from './assets/vaso-300cc.png';
import img12 from './assets/vaso-500cc.png';
import img13 from './assets/vaso-termico-10oz.png';
import img14 from './assets/mentholatum.png';
import img15 from './assets/hombre-gillete-2.png';
import img16 from './assets/hombre-schick-4.png';
import img17 from './assets/mujer-schick-4.png';
import img18 from './assets/venus.png';
import img19 from './assets/cepillo-colgate-13.png';
import img20 from './assets/crema-dental-colgate.png';
import img21 from './assets/crema-dental-pepsodent-whithing.png';
import img22 from './assets/jabon-lux-pack-4.png';
import img23 from './assets/kingdom.png';
import img24 from './assets/test-de-embarazo.png';
import img25 from './assets/toalla-humeda-babysec.png';
import img26 from './assets/toalla-morada-tela-suave.png';
import img27 from './assets/lady-soft-noche-ultraseca.png';
import img28 from './assets/lady-soft-normal-verde.png';
import img29 from './assets/vaporal-12.png';
import img30 from './assets/encendedor-ronson-display.png';
import img31 from './assets/papel-fino-ronson.png';
import img32 from './assets/pack-encendedor-lin.png';
import img33 from './assets/parche-curita-cure-band.png';
import img34 from './assets/cinta-de-embalaje-100mts.png';
import img35 from './assets/cinta-de-embalaje-50mts.png';
import img36 from './assets/chemmer-12.png';
import img37 from './assets/la-gotita.png';

export default {
  "bolsa-mini.png": img0,
  "bolsa-mediana.png": img1,
  "bolsa-grande.png": img2,
  "bolsa-jumbo.png": img3,
  "bolsa-botillera.png": img4,
  "rollo-pullpack-700.png": img5,
  "bolsa-de-ensalada.png": img6,
  "bolsa-taco-manga.png": img7,
  "guante-de-nitrilo.png": img8,
  "guante-de-vinilo.png": img9,
  "guantes-polietileno.png": img10,
  "vaso-300cc.png": img11,
  "vaso-500cc.png": img12,
  "vaso-termico-10oz.png": img13,
  "mentholatum.png": img14,
  "hombre-gillete-2.png": img15,
  "hombre-schick-4.png": img16,
  "mujer-schick-4.png": img17,
  "venus.png": img18,
  "cepillo-colgate-13.png": img19,
  "crema-dental-colgate.png": img20,
  "crema-dental-pepsodent-whithing.png": img21,
  "jabon-lux-pack-4.png": img22,
  "kingdom.png": img23,
  "test-de-embarazo.png": img24,
  "toalla-humeda-babysec.png": img25,
  "toalla-morada-tela-suave.png": img26,
  "lady-soft-noche-ultraseca.png": img27,
  "lady-soft-normal-verde.png": img28,
  "vaporal-12.png": img29,
  "encendedor-ronson-display.png": img30,
  "papel-fino-ronson.png": img31,
  "pack-encendedor-lin.png": img32,
  "parche-curita-cure-band.png": img33,
  "cinta-de-embalaje-100mts.png": img34,
  "cinta-de-embalaje-50mts.png": img35,
  "chemmer-12.png": img36,
  "la-gotita.png": img37,
};
